export const usersData = [
  {
    email: "samirshahi9882@gmail.com",
    firstname: "Sameer",
    lastname: "Shahi",
    username: "sameershahithakuri",
    password: "coder123",
    bio: "Creative Mind",
    address: "kupandole,Kathmandu",
    role: "USER",
  },
  {
    email: "anjansth@gmail.com",
    firstname: "Anjan",
    lastname: "Shrestha",
    username: "anjansrestha",
    password: "coder123",
    bio: "Passionate Learner",
    address: "Mahendrapool,Pokhara",
    role: "USER",
  },
  {
    email: "rokarajan@gmail.com",
    firstname: "Rajan",
    lastname: "Roka",
    username: "rokaRajan",
    password: "coder123",
    bio: "Aspiring mind",
    address: "Parsa,Chitwan",
    role: "USER",
  },
  {
    email: "thapamilan96@gmail.com",
    firstname: "Milan",
    lastname: "Thapa",
    username: "iammilan",
    password: "coder123",
    bio: "Adventorous",
    address: "Parsa,Chitwan",
    role: "USER",
  },
  {
    email: "sthsafal25.com",
    firstname: "Safal",
    lastname: "Shrestha",
    username: "itsmesafal",
    password: "coder123",
    bio: "BookWorm",
    address: "Tadi,Chitwan",
    role: "USER",
  },
  // New objects with real names, same password, and role "MENTOR"
  {
    email: "bhujelbishal23@gmail.com",
    firstname: "Bishal",
    lastname: "Bhujel",
    username: "Bhujelbishal",
    password: "coder123",
    bio: "Innovative",
    address: "Chabel,Kathmandu",
    role: "MENTOR",
  },
  {
    email: "ronishrai@gmail.com",
    firstname: "Ronish",
    lastname: "Rai",
    username: "rai@24",
    password: "coder123",
    bio: "Strategic Mind",
    address: "Itahari",
    role: "MENTOR",
  },
  {
    email: "sarahbhattarai@gmail.com",
    firstname: "Sarah",
    lastname: "bhattarai",
    username: "sarah@307",
    password: "coder123",
    bio: "Enthusiastic Guider",
    address: "Address for Sarah",
    role: "MENTOR",
  },
  {
    email: "mikelshah@gmail.com",
    firstname: "Mikel",
    lastname: "Shah",
    username: "itsmemikel",
    password: "coder123",
    bio: "Inclusion mentor",
    address: "Thapathali,Kathmandu",
    role: "MENTOR",
  },
  {
    email: "gyanwalitech@gmail.com",
    firstname: "Resham",
    lastname: "Gyanwali",
    username: "resham@465",
    password: "coder123",
    bio: "Compassionate",
    address: "Bagar,Pokhara",
    role: "MENTOR",
  },
  {
    email: "thapaamit@gmail.com",
    firstname: "Amit",
    lastname: "thapa",
    username: "Coderamit",
    password: "coder123",
    bio: "Tech Enthusiast",
    address: "Lalitpur",
    role: "MENTOR",
  },
  {
    email: "girieva@gmail.com",
    firstname: "Eva",
    lastname: "Giri",
    username: "Eva@688",
    password: "coder123",
    bio: "Diversified",
    address: "Bhaktapur",
    role: "MENTOR",
  },
  {
    email: "jamessth@gmail.com",
    firstname: "James",
    lastname: "Shrestha",
    username: "Jamessth",
    password: "coder123",
    bio: "Passionate ",
    address: "Birauta,Pokhara",
    role: "MENTOR",
  },
  {
    email: "alishachetri@gmail.com",
    firstname: "Alisha",
    lastname: "Chettri",
    username: "alu@123",
    password: "coder123",
    bio: "Live,Learn,Life",
    address: "Kalanki,Kathmandu",
    role: "MENTOR",
  },
  // Remaining objects can follow a similar pattern
];
