export const usersData = [
  {
    email: "samirshahi9882@gmail.com",
    firstname: "Sameer",
    lastname: "Shahi",
    username: "sameershahithakuri",
    password: "coder123",
    bio: "Creative Mind",
    address: "kupandole,Kathmandu",
    role: "USER",
    thumbnail:"https://res.cloudinary.com/dvj4qsyeu/image/upload/v1709736551/pexels-photo-2379004_y2qddu.jpg",
  },
  {
    email: "anjansth@gmail.com",
    firstname: "Anjan",
    lastname: "Shrestha",
    username: "anjansrestha",
    password: "coder123",
    bio: "Passionate Learner",
    address: "Mahendrapool,Pokhara",
    role: "USER",
    thumbnail:"https://res.cloudinary.com/dvj4qsyeu/image/upload/v1709735644/pep4_s8z0j9.jpg",
  },
  {
    email: "rokarajan@gmail.com",
    firstname: "Rajan",
    lastname: "Roka",
    username: "rokaRajan",
    password: "coder123",
    bio: "Aspiring mind",
    address: "Parsa,Chitwan",
    role: "USER",
    thumbnail:"https://res.cloudinary.com/dvj4qsyeu/image/upload/v1709735643/pep3_xetaak.jpg",
  },
  {
    email: "thapamilan96@gmail.com",
    firstname: "Milan",
    lastname: "Thapa",
    username: "iammilan",
    password: "coder123",
    bio: "Adventorous",
    address: "Parsa,Chitwan",
    role: "USER",
    thumbnail:"https://res.cloudinary.com/dvj4qsyeu/image/upload/v1709735643/pep6_xsqmag.avif",
  },
  {
    email: "sthsafal25.com",
    firstname: "Safal",
    lastname: "Shrestha",
    username: "itsmesafal",
    password: "coder123",
    bio: "BookWorm",
    address: "Tadi,Chitwan",
    role: "USER",
    thumbnail:"https://res.cloudinary.com/dvj4qsyeu/image/upload/v1709736266/white-male-student-notebook_tcm18-336857_ibglx5.jpg",
  },

  // New objects with real names, same password, and role "MENTOR"
  {
    email: "bhujelbishal23@gmail.com",
    firstname: "Bishal",
    lastname: "Bhujel",
    username: "Bhujelbishal",
    password: "coder123",
    bio: "Innovative",
    address: "Chabel,Kathmandu",
    role: "MENTOR",
    thumbnail:"https://res.cloudinary.com/dvj4qsyeu/image/upload/v1709736266/3244_Home-for-Summer-S24-Rotator.rev.1702415677_qpmdu4.jpg",
  },
  {
    email: "ronishrai@gmail.com",
    firstname: "Ronish",
    lastname: "Rai",
    username: "rai@24",
    password: "coder123",
    bio: "Strategic Mind",
    address: "Itahari",
    role: "MENTOR",
    thumbnail:"https://res.cloudinary.com/dvj4qsyeu/image/upload/v1709736266/college-student-glasses-backpack_bliunr.jpg",
  },
  {
    email: "sarahbhattarai@gmail.com",
    firstname: "Sarah",
    lastname: "bhattarai",
    username: "sarah@307",
    password: "coder123",
    bio: "Enthusiastic Guider",
    address: "Address for Sarah",
    role: "MENTOR",
    thumbnail:"https://res.cloudinary.com/dvj4qsyeu/image/upload/v1709736438/young-asian-woman-student-in-uniform-using-smartphone-about-work-there-are-many-documents-on-the-table-her-face-with-smiling-in-a-working-at-to-search-information-for-a-study-report-at-university-photo_zexk5n.jpg",
  },
  {
    email: "mikelshah@gmail.com",
    firstname: "Mikel",
    lastname: "Shah",
    username: "itsmemikel",
    password: "coder123",
    bio: "Inclusion mentor",
    address: "Thapathali,Kathmandu",
    role: "MENTOR",
    thumbnail:"https://res.cloudinary.com/dvj4qsyeu/image/upload/v1709706318/samples/smile.jpg",
  },
  {
    email: "gyanwalitech@gmail.com",
    firstname: "Resham",
    lastname: "Gyanwali",
    username: "resham@465",
    password: "coder123",
    bio: "Compassionate",
    address: "Bagar,Pokhara",
    role: "MENTOR",
    thumbnail:"https://res.cloudinary.com/dvj4qsyeu/image/upload/v1709706294/samples/people/smiling-man.jpg",
  },
  
  {
    email: "girieva@gmail.com",
    firstname: "Eva",
    lastname: "Giri",
    username: "Eva@688",
    password: "coder123",
    bio: "Diversified",
    address: "Bhaktapur",
    role: "MENTOR",
    thumbnail:"https://res.cloudinary.com/dvj4qsyeu/image/upload/v1709735643/pep2_y373rr.jpg",
  },
  {
    email: "jamessth@gmail.com",
    firstname: "James",
    lastname: "Shrestha",
    username: "Jamessth",
    password: "coder123",
    bio: "Passionate ",
    address: "Birauta,Pokhara",
    role: "MENTOR",
    thumbnail:"https://res.cloudinary.com/dvj4qsyeu/image/upload/v1709736668/What-Is-A-Sigma-Male-And-Their-Common-Personality-Trait-624x702_m8asne.jpg",
  },
  {
    email: "alishachetri@gmail.com",
    firstname: "Alisha",
    lastname: "Chettri",
    username: "alu@123",
    password: "coder123",
    bio: "Live,Learn,Life",
    address: "Kalanki,Kathmandu",
    role: "MENTOR",
    thumbnail:"https://res.cloudinary.com/dvj4qsyeu/image/upload/v1709735643/pep1_uufjiy.jpg",
  },
  // Remaining objects can follow a similar pattern
];
